### PR TITLE
Fix use of deprecated EOS.undent

### PR DESCRIPTION
**Pull request by patreeceeo**
See: https://github.com/Homebrew/brew/issues/3738

### CODE REVIEW

**Comment by PorgJuice** [comment]
@sjrmanning Is there something blocking this PR?

**Comment by mateusfccp** [comment]
Why this haven't been merged yet? It is blocking a lot of people from using this tap, but it is simple and won't cause any issue.

**Comment by mabuchner** [comment]
Since #12 got merged, this pull request can get closed.

**Comment by filipw** [comment]
thank you for your efforts - #12 got merged so this is now no longer needed

**Pull request closed without merging**
